export const IS_AUTHORIZED = 'IS_AUTHORIZED'
export const ADD_PHONE_NUMBER = 'ADD_PHONE_NUMBER'
export const ADD_USER_INFORMATION = 'ADD_USER_INFORMATION'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCT_RANGE = 'FETCH_PRODUCT_RANGE'

// Category
export const FETCH_HOT_DEAL = 'FETCH_HOT_DEAL'
export const FETCH_PHONG_VU_CHOICE = 'FETCH_PHONG_VU_CHOICE'
export const FETCH_OFFICER_CHOICE = 'FETCH_OFFICER_CHOICE'
export const FETCH_IT_CHOICE = 'FETCH_IT_CHOICE'

// Detail
export const FETCH_SAME_BRAND_PRODUCTS = 'FETCH_SAME_BRAND_PRODUCTS'
export const FETCH_SIMILAR_PRODUCTS = 'FETCH_SIMILAR_PRODUCTS'
